### ISSUE TITLE
ERROR - No module named rpi_rf2

### ISSUE THREAD

**Issue by ckrack** [filipematos95/cbpi-socket433#1]
I see this in my logs.
The``rpi_rf.py``file exists, but no compiled version.

Any idea?

**Comment by johannesrave** [comment]
How and when do you even see that error? In the CBPi interface or on the command line somewhere? I can't get the plugin to run - it just never appears in my Hardware Settings :(

**Comment by ckrack** [comment]
In the logfile

**Comment by johannesrave** [comment]
hey ckrack,
i think there is a bug in __init__.py on line 2:
`from rpi_rf2 import RFDevice`
it should instead say:
`from rpi_rf import RFDevice`

the plugin works now on my craftbeerpi.

**Comment by filipematos95** [comment]
@cutmeat is correct. I just corrected that bug
